[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pumpdotfun = "YoBKRApxG4TVThpMaBVcg8ewoMrmHHrrotiFBVX6snW"

[programs.devnet]
pumpdotfun = "YoBKRApxG4TVThpMaBVcg8ewoMrmHHrrotiFBVX6snW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/Desktop/SounDAO/baySMce3jxfnxTH1UivnFaDVXQRpTxziGU2YgnKFRNy.json"

[scripts]
client = "yarn run ts-node client/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
